// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/municion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Keys int64  `protobuf:"varint,2,opt,name=keys,proto3" json:"keys,omitempty"`
}

func (x *Notify) Reset() {
	*x = Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_municion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_municion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_proto_municion_proto_rawDescGZIP(), []int{0}
}

func (x *Notify) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Notify) GetKeys() int64 {
	if x != nil {
		return x.Keys
	}
	return 0
}

type RegUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsersNoreg int64 `protobuf:"varint,1,opt,name=users_noreg,json=usersNoreg,proto3" json:"users_noreg,omitempty"`
	UsersReg   int64 `protobuf:"varint,2,opt,name=users_reg,json=usersReg,proto3" json:"users_reg,omitempty"`
}

func (x *RegUsers) Reset() {
	*x = RegUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_municion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUsers) ProtoMessage() {}

func (x *RegUsers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_municion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUsers.ProtoReflect.Descriptor instead.
func (*RegUsers) Descriptor() ([]byte, []int) {
	return file_proto_municion_proto_rawDescGZIP(), []int{1}
}

func (x *RegUsers) GetUsersNoreg() int64 {
	if x != nil {
		return x.UsersNoreg
	}
	return 0
}

func (x *RegUsers) GetUsersReg() int64 {
	if x != nil {
		return x.UsersReg
	}
	return 0
}

var File_proto_municion_proto protoreflect.FileDescriptor

var file_proto_municion_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x30, 0x0a, 0x06,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x48,
	0x0a, 0x08, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x5f, 0x6e, 0x6f, 0x72, 0x65, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x73, 0x4e, 0x6f, 0x72, 0x65, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x5f, 0x72, 0x65, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x67, 0x32, 0x64, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x08, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x1a, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x2b, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x0e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x0e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_municion_proto_rawDescOnce sync.Once
	file_proto_municion_proto_rawDescData = file_proto_municion_proto_rawDesc
)

func file_proto_municion_proto_rawDescGZIP() []byte {
	file_proto_municion_proto_rawDescOnce.Do(func() {
		file_proto_municion_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_municion_proto_rawDescData)
	})
	return file_proto_municion_proto_rawDescData
}

var file_proto_municion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_municion_proto_goTypes = []interface{}{
	(*Notify)(nil),   // 0: grpc.Notify
	(*RegUsers)(nil), // 1: grpc.RegUsers
}
var file_proto_municion_proto_depIdxs = []int32{
	0, // 0: grpc.NotifyService.Exchange:input_type -> grpc.Notify
	1, // 1: grpc.NotifyService.SendUsers:input_type -> grpc.RegUsers
	0, // 2: grpc.NotifyService.Exchange:output_type -> grpc.Notify
	1, // 3: grpc.NotifyService.SendUsers:output_type -> grpc.RegUsers
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_municion_proto_init() }
func file_proto_municion_proto_init() {
	if File_proto_municion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_municion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_municion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_municion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_municion_proto_goTypes,
		DependencyIndexes: file_proto_municion_proto_depIdxs,
		MessageInfos:      file_proto_municion_proto_msgTypes,
	}.Build()
	File_proto_municion_proto = out.File
	file_proto_municion_proto_rawDesc = nil
	file_proto_municion_proto_goTypes = nil
	file_proto_municion_proto_depIdxs = nil
}
